version: 2
updates:
  - package-ecosystem: gomod
    directory: /app
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test-smoke
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test-integration
    schedule:
      interval: daily