global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    scheme: http
    metrics_path: /api/status/metrics
    static_configs:
      - targets: [ 'app:8080' ]