# Global config
region: EU
environment: TEST

# Server config
server:
  port: 8443
  timeout:
    read: 10
    write: 10
    idle: 10

# Logger config
logger:
  level: INFO
  json: true

# Database config
database:
  host: postgresql.eu-test
  port: 5432
  user: "InFutureNeedToInjectEnvVar"
  password: "SdzA7vp6GPPUNRjnelSs"
  database: "test_db"
  max_idle_connections: 10
  max_open_connections: 90
