version: '3.9'

networks:
  default:
    name: order-service

services:
  app:
    image: ghcr.io/valentinlutz/order-service:latest
    build:
      context: ../../../
      dockerfile: ./services/order/app/Dockerfile
    container_name: app
    volumes:
      - ../config/app/config.none-container.yaml:/app/config/config.yaml:ro
      - ../config/app.crt:/app/config/app.crt:ro
      - ../config/app.key:/app/config/app.key:ro
    ports:
      - '9433:8433'

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    depends_on:
      - app
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9091:9090'
